### ISSUE TITLE
Modifiable web interface

### ISSUE THREAD

**Issue by sf985** [synesthesiam/docker-marytts#1]
Hi there, firstly, my apologies if this is not the right place/way to ask this question, I'm new to everything. Secondly, a huge thank you for working on this! I recently found out a friend of mine's father had a stroke and can't speak, but can move his hands and head, so I'm trying to make some kind of text to speech for him to use so his family can talk to him over the phone (with the pandemic its one of the few ways they can communicate, but not at all since his stroke). To my Q: I have successfully followed installation from scratch on a Raspberry Pi that I can get the server up and running and get text to speech on any device on the network through the web interface. I am having some interaction-design related issues with the web interface though and wonder if there is a file somewhere I can modify for myself that will change the layout/sizes etc of the boxes and dropdowns in the interface? Thanks again!

**Comment by aabeling** [comment]
This project just uses a release from https://github.com/marytts/marytts.
If you want to change the layout of the interface you will have to build your own release of marytts, I suppose.
You will find the corresponding html in 
https://github.com/marytts/marytts/blob/v5.2/marytts-runtime/src/main/resources/marytts/server/http/index.html
Alternatively you can build your own html page with an embedded player like in the marytts index.html which plays something like
http://localhost:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=Willkommen%20in%20der%20Welt%20der%20Sprachsynthese!%0A&VOICE_SELECTIONS=bits1-hsmm%20de%20female%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=de&VOICE=bits1-hsmm&AUDIO=WAVE_FILE
